### ISSUE TITLE
Try this year's  task

### ISSUE THREAD

**Issue by chumingqian** [HUJH511/BioCAS-2023-Grand_Challenge#1]
Hello, author:
        Have you tried this year's  tasks,  like  sound  event detection.

**Comment by HUJH511** [comment]
Our team tried compression track this year

**Comment by chumingqian** [comment]
@HUJH511 , 
Ok,  thanks  for  your reply,  by the way.    
 If you are plan to make the code for the compression track publicly available, please let me know, I'm also curious about this task.
Thanks in advance.
